### ISSUE TITLE
echo

### ISSUE THREAD

**Issue by briansimoni** [briansimoni/Go-Shell#4]
echo <comment> - Display <comment> on the display followed by a
new line (multiple spaces/tabs may be reduced to a single space).

**Comment by herbertkb** [comment]
Mostly done. I tweaked it to print the entire line of arguments. Not sure if we should bother with reducing multiple spaces/tabs to single space. What if someone is using echo to set up a table of output in a script? Or wants to draw some sick ASCII art?
