### ISSUE TITLE
All other command line input is interpreted as program invocation

### ISSUE THREAD

**Issue by briansimoni** [briansimoni/Go-Shell#9]
All other command line input is interpreted as program invocation,
which should be done by the shell forking and execing the programs as
its own child processes. The programs should be executed with an
environment that contains the entry: parent=<pathname>/myshell
where <pathname>/myshell is as described in 1.ix. above.

**Comment by herbertkb** [comment]
Done! 257421414de3909af307fdb37458d1bfc40da2d9 and 31bb39d556e40d6e9a47b1afc30ef2d8557b0e8b
